// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxCRHvTnjwTGb_riGZFFKAzdTj6E3B_Hw',
    appId: '1:247129587614:web:35c4827aa1c0522dd8208f',
    messagingSenderId: '247129587614',
    projectId: 'flutter-reddit-clone-14f64',
    authDomain: 'flutter-reddit-clone-14f64.firebaseapp.com',
    databaseURL: 'https://flutter-reddit-clone-14f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reddit-clone-14f64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleiuUoVlWXhRZVw4pPh1wp5Oiq558GME',
    appId: '1:247129587614:android:568aca3e6ea4bd6ed8208f',
    messagingSenderId: '247129587614',
    projectId: 'flutter-reddit-clone-14f64',
    databaseURL: 'https://flutter-reddit-clone-14f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reddit-clone-14f64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXGDuSe9JypuW7jD3h6PR2vkDe3BCMnA',
    appId: '1:247129587614:ios:dd117b7c756da2b6d8208f',
    messagingSenderId: '247129587614',
    projectId: 'flutter-reddit-clone-14f64',
    databaseURL: 'https://flutter-reddit-clone-14f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reddit-clone-14f64.appspot.com',
    iosClientId: '247129587614-si0fv6uuhsus5b3oe9f2ste3ph6l8hq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqXGDuSe9JypuW7jD3h6PR2vkDe3BCMnA',
    appId: '1:247129587614:ios:dd117b7c756da2b6d8208f',
    messagingSenderId: '247129587614',
    projectId: 'flutter-reddit-clone-14f64',
    databaseURL: 'https://flutter-reddit-clone-14f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reddit-clone-14f64.appspot.com',
    iosClientId: '247129587614-si0fv6uuhsus5b3oe9f2ste3ph6l8hq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
